kind: pipeline
name: default
clone:
  disable: true
steps:
  - name: 拉取代码
    image: alpine/git
    pull: if-not-exists
    commands:
      - git config --global http.version HTTP/1.1
      - git clone ${DRONE_GIT_HTTP_URL} .
      - git checkout $DRONE_COMMIT
  - name: 生成静态资源
    pull: if-not-exists
    image: hugomods/hugo
    commands:
      - git config --global http.version HTTP/1.1
      - cd themes/vendor && yarn && yarn build && cd ../..
      - rm /tmp/cache/${DRONE_BRANCH}/* -fr
      - hugo --minify --destination /tmp/cache/${DRONE_BRANCH}
      - chmod -R 744 /tmp/cache/${DRONE_BRANCH}
    volumes:
      - name: html
        path: /tmp/cache
trigger:
  branch:
    - dev
    - main
volumes:
  - name: html
    host:
      path: /data/html
