kind: pipeline
name: default

steps:
  - name: 生成静态资源
    pull: if-not-exists
    image: hugomods/hugo
    commands:
      - cd themes/vendor && yarn && yarn build && cd ../..
      - rm data/html/* -fr
      - hugo --minify --destination /tmp/cache
    volumes:
      - name: html
        path: /tmp/cache
volumes:
  - name: html
    host:
      path: /data/html